### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaspic#44]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by arjantijms** [comment]
JASPIC has no compile time dependencies, so should be good to go then,

**Comment by arjantijms** [comment]
JASPIC has been released: https://repo1.maven.org/maven2/jakarta/security/auth/message/jakarta.security.auth.message-api/1.1.2/
