### ISSUE TITLE
Update Scope Statement for Jakarta Authentication Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaspic#45]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by smillidge** [comment]
@arjantijms can you draft a new scope statement from the old one?

**Comment by ivargrimstad** [comment]
Jakarta Authentication defines a service provider interface (SPI) by which authentication providers implementing message authentication mechanisms may be integrated with client or server message processing containers or runtimes.

**Comment by arjantijms** [comment]
@ivargrimstad  Perhaps the scope statement should address that JASPIC exists of profiles, where each profiles tells a container (like Servlet, or a JAX-WS/SOAP one) how to provide the SPI. The SPI is "low-level", meaning not really targeting application developers. A small explanation of what "authentication mechanism" means in this context may be beneficial:

> Jakarta Authentication defines a general low-level SPI for authentication mechanisms, which are controllers that interact with a caller and a container's environment, and several  profiles, with each profile telling how a specific container (such as Servlet) can integrate with- and adapt to this SPI.

Optionally, somewhat longer:

> Jakarta Authentication defines a general low-level SPI for authentication mechanisms, which are controllers that interact with a caller and a container's environment to obtain the caller's credentials, validate these, and pass an authenticated identity (such as name and groups) to the container. Jakarta Authentication consists of several  profiles, with each profile telling how a specific container (such as Servlet) can integrate with- and adapt to this SPI.
