### ISSUE TITLE
Change project name to Jakarta Authentication

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaspic#46]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Is it ok to leave out ...Service Provider Interface for Containers?
Is there a way to mark it as an SPI without a too long name?

**Comment by ggam** [comment]
> Is it ok to leave out ...Service Provider Interface for Containers?

+1 for simpler/shorther names.

**Comment by arjantijms** [comment]
I’ve been thinking a lot about this too.

On the one hand it’s an SPI and doesn’t provide much concrete functionality, on the other hand there is the factory class, which is not really an SPI but more like an API.

A similar thing holds for JACC to some degree.

At the end of the day I think it’s a trade of between making it ultra clear what the scope of the spec is (authentication), vs adding more words to be more exact.

I think the proposed “Jakarta Authentication” is the best though.

**Comment by ggam** [comment]
IMO, people tend to associate those long, mysterious names with heavyweight, arcane J2EE.

The only I see is that people might get confused with the differences between "Jakarta Authentication", "Jakarta Authorization" and "Jakarta Security". Ideally we could find a name like "Jakarta Authentication Foundation" or "Jakarta Authentication Services" that can be used to describe a low level layer on top of which a user-facing API (Jakarta Security) can be built.

**Comment by arjantijms** [comment]
The confusion is a small concern indeed, but we may update the javadoc of most Jaspic types, explaining it’s an SPI mostly, and that user apps should probably want to look at Jakarta Security.

**Comment by arjantijms** [comment]
@ggam and others, if no-one has any pressing concerns against the proposed name I'd like to go ahead and start the renaming next week.

**Comment by ggam** [comment]
+1 from me although (as everyone, I suspect) I'd like names to be
consistent between projects. I'm a bit worried about JAX-RS going a
different path right after us. Should we raise this concern on the platform
list before commiting the change?

**Comment by arjantijms** [comment]
>Should we raise this concern on the platform list before commiting the change?

Yes that would be a good idea, before doing any actual changes it would be good anyway to see if any other projects would want to go in a different direction.

**Comment by bshannon** [comment]
I think "Jakarta Authentication" is good enough.
I like the fact that most of these projects will end
up with the simplest possible name.

**Comment by smillidge** [comment]
I would go with "Jakarta Authentication" given JACC is going to "Jakarta Authorization" it has a consistent feel.

**Comment by arjantijms** [comment]
@ivargrimstad with "GitHub" do you mean the project name this GitHub repo shows?

E.g. eclipse-ee4j/jaspic to eclipse-ee4j/jakarta-authentication or just the description shown here:

<img width="1014" alt="github-jaspic" src="https://user-images.githubusercontent.com/3037006/61060483-e32c6600-a3fa-11e9-8cd4-890dbe1a18b0.png">
