### ISSUE TITLE
Prepare Jakarta Authentication for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaspic#49]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by arjantijms** [comment]
"Make a staging release" currently blocked on credentials not working anymore. Filed a bug for this:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=549251

**Comment by arjantijms** [comment]
Credentials actually did appear to work (the message is somewhat misleading perhaps), but it's just the spec artefact that can't be staged. Staging just API works, and has been done now:

https://oss.sonatype.org/content/repositories/staging/jakarta/security/auth/message/jakarta.security.auth.message-api/1.1.3/

**Comment by arjantijms** [comment]
* [Staging release](https://oss.sonatype.org/content/repositories/staging/jakarta/security/auth/message/jakarta.security.auth.message-api/1.1.3/)
* [TCK results](https://jenkins.eclipse.org/jaspic/job/2_authentication_run_tck_against_staged_build/lastSuccessfulBuild/artifact/jaspictck/bin/summary.txt/*view*/)
* [Spec PR 1](https://github.com/jakartaee/specifications/pull/38)
* [Spec PR 2](https://github.com/jakartaee/specifications/pull/39)

**Comment by m0mus** [comment]
Reopening because new tasks were added.

**Comment by arjantijms** [comment]
[API PR](https://github.com/eclipse-ee4j/jakartaee-api/pull/14)

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549719)
